webhooks:
  svstatus: "https://discord.com/api/webhooks/xxxxx/svstatus"
  join: "https://discord.com/api/webhooks/xxxxx/join"
  quit: "https://discord.com/api/webhooks/xxxxx/quit"
  chat: "https://discord.com/api/webhooks/xxxxx/chat"
  death: "https://discord.com/api/webhooks/xxxxx/death"
  breakblock: "https://discord.com/api/webhooks/xxxxx/block"
  craft: "https://discord.com/api/webhooks/xxxxx/craft"
  pickup: "https://discord.com/api/webhooks/xxxxx/pickup"
  drop: "https://discord.com/api/webhooks/xxxxx/drop"
  gamemode: "https://discord.com/api/webhooks/xxxxx/gamemode"
  worldchange: "https://discord.com/api/webhooks/xxxxx/world"
  usecommand: "https://discord.com/api/webhooks/xxxxx/usecommand"