webhooks:
  svstatus: ""
  join: ""
  quit: ""
  chat: ""
  death: ""
  breakblock: ""
  craft: ""
  pickup: ""
  drop: ""
  gamemode: ""
  worldchange: ""
  usecommand: ""
  advancement: ""
  mobkills: ""
  weather: ""
  itembreak: ""
