name: DiscordLogger
version: '1.5-release'
main: mathew.discordLogger.DiscordLogger
api-version: '1.21'
authors: [ matthewnx ]
description: log minecraft events to discord
website: https://github.com/matthewnx
